//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCFDI.WsFacturador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://facturadorelectronico.com/timbrado/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/", ConfigurationName="WsFacturador.wsTimbradoSoap")]
    public interface wsTimbradoSoap {
        
        // CODEGEN: Generating message contract since element name xmlCancelacion from namespace http://facturadorelectronico.com/timbrado/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/cancelarComprobante", ReplyAction="*")]
        PruebaCFDI.WsFacturador.cancelarComprobanteResponse cancelarComprobante(PruebaCFDI.WsFacturador.cancelarComprobanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/cancelarComprobante", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.cancelarComprobanteResponse> cancelarComprobanteAsync(PruebaCFDI.WsFacturador.cancelarComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name xmlCancelacion from namespace http://facturadorelectronico.com/timbrado/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/CancelarComprobanteRetenciones", ReplyAction="*")]
        PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponse CancelarComprobanteRetenciones(PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/CancelarComprobanteRetenciones", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponse> CancelarComprobanteRetencionesAsync(PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://facturadorelectronico.com/timbrado/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/EnviarCancelacionPFX", ReplyAction="*")]
        PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponse EnviarCancelacionPFX(PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/EnviarCancelacionPFX", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponse> EnviarCancelacionPFXAsync(PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest request);
        
        // CODEGEN: Generating message contract since element name CFDIcliente from namespace http://facturadorelectronico.com/timbrado/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/obtenerTimbrado", ReplyAction="*")]
        PruebaCFDI.WsFacturador.obtenerTimbradoResponse obtenerTimbrado(PruebaCFDI.WsFacturador.obtenerTimbradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facturadorelectronico.com/timbrado/obtenerTimbrado", ReplyAction="*")]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.obtenerTimbradoResponse> obtenerTimbradoAsync(PruebaCFDI.WsFacturador.obtenerTimbradoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelarComprobante", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.cancelarComprobanteRequestBody Body;
        
        public cancelarComprobanteRequest() {
        }
        
        public cancelarComprobanteRequest(PruebaCFDI.WsFacturador.cancelarComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class cancelarComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlCancelacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public cancelarComprobanteRequestBody() {
        }
        
        public cancelarComprobanteRequestBody(string xmlCancelacion, string usuario, string password) {
            this.xmlCancelacion = xmlCancelacion;
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelarComprobanteResponse", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.cancelarComprobanteResponseBody Body;
        
        public cancelarComprobanteResponse() {
        }
        
        public cancelarComprobanteResponse(PruebaCFDI.WsFacturador.cancelarComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class cancelarComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement cancelarComprobanteResult;
        
        public cancelarComprobanteResponseBody() {
        }
        
        public cancelarComprobanteResponseBody(System.Xml.Linq.XElement cancelarComprobanteResult) {
            this.cancelarComprobanteResult = cancelarComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarComprobanteRetencionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarComprobanteRetenciones", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequestBody Body;
        
        public CancelarComprobanteRetencionesRequest() {
        }
        
        public CancelarComprobanteRetencionesRequest(PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class CancelarComprobanteRetencionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlCancelacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuariotimbrado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string passwordtimbrado;
        
        public CancelarComprobanteRetencionesRequestBody() {
        }
        
        public CancelarComprobanteRetencionesRequestBody(string xmlCancelacion, string usuariotimbrado, string passwordtimbrado) {
            this.xmlCancelacion = xmlCancelacion;
            this.usuariotimbrado = usuariotimbrado;
            this.passwordtimbrado = passwordtimbrado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarComprobanteRetencionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarComprobanteRetencionesResponse", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponseBody Body;
        
        public CancelarComprobanteRetencionesResponse() {
        }
        
        public CancelarComprobanteRetencionesResponse(PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class CancelarComprobanteRetencionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement CancelarComprobanteRetencionesResult;
        
        public CancelarComprobanteRetencionesResponseBody() {
        }
        
        public CancelarComprobanteRetencionesResponseBody(System.Xml.Linq.XElement CancelarComprobanteRetencionesResult) {
            this.CancelarComprobanteRetencionesResult = CancelarComprobanteRetencionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCancelacionPFXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCancelacionPFX", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequestBody Body;
        
        public EnviarCancelacionPFXRequest() {
        }
        
        public EnviarCancelacionPFXRequest(PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class EnviarCancelacionPFXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PruebaCFDI.WsFacturador.ArrayOfString uuids;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] pfx;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string passwordPfx;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rfc;
        
        public EnviarCancelacionPFXRequestBody() {
        }
        
        public EnviarCancelacionPFXRequestBody(string usuario, string password, PruebaCFDI.WsFacturador.ArrayOfString uuids, byte[] pfx, string passwordPfx, string rfc) {
            this.usuario = usuario;
            this.password = password;
            this.uuids = uuids;
            this.pfx = pfx;
            this.passwordPfx = passwordPfx;
            this.rfc = rfc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCancelacionPFXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCancelacionPFXResponse", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponseBody Body;
        
        public EnviarCancelacionPFXResponse() {
        }
        
        public EnviarCancelacionPFXResponse(PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class EnviarCancelacionPFXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement EnviarCancelacionPFXResult;
        
        public EnviarCancelacionPFXResponseBody() {
        }
        
        public EnviarCancelacionPFXResponseBody(System.Xml.Linq.XElement EnviarCancelacionPFXResult) {
            this.EnviarCancelacionPFXResult = EnviarCancelacionPFXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerTimbradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerTimbrado", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.obtenerTimbradoRequestBody Body;
        
        public obtenerTimbradoRequest() {
        }
        
        public obtenerTimbradoRequest(PruebaCFDI.WsFacturador.obtenerTimbradoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class obtenerTimbradoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CFDIcliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public obtenerTimbradoRequestBody() {
        }
        
        public obtenerTimbradoRequestBody(string CFDIcliente, string Usuario, string password) {
            this.CFDIcliente = CFDIcliente;
            this.Usuario = Usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerTimbradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerTimbradoResponse", Namespace="http://facturadorelectronico.com/timbrado/", Order=0)]
        public PruebaCFDI.WsFacturador.obtenerTimbradoResponseBody Body;
        
        public obtenerTimbradoResponse() {
        }
        
        public obtenerTimbradoResponse(PruebaCFDI.WsFacturador.obtenerTimbradoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://facturadorelectronico.com/timbrado/")]
    public partial class obtenerTimbradoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement obtenerTimbradoResult;
        
        public obtenerTimbradoResponseBody() {
        }
        
        public obtenerTimbradoResponseBody(System.Xml.Linq.XElement obtenerTimbradoResult) {
            this.obtenerTimbradoResult = obtenerTimbradoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTimbradoSoapChannel : PruebaCFDI.WsFacturador.wsTimbradoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTimbradoSoapClient : System.ServiceModel.ClientBase<PruebaCFDI.WsFacturador.wsTimbradoSoap>, PruebaCFDI.WsFacturador.wsTimbradoSoap {
        
        public wsTimbradoSoapClient() {
        }
        
        public wsTimbradoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTimbradoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTimbradoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTimbradoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaCFDI.WsFacturador.cancelarComprobanteResponse PruebaCFDI.WsFacturador.wsTimbradoSoap.cancelarComprobante(PruebaCFDI.WsFacturador.cancelarComprobanteRequest request) {
            return base.Channel.cancelarComprobante(request);
        }
        
        public System.Xml.Linq.XElement cancelarComprobante(string xmlCancelacion, string usuario, string password) {
            PruebaCFDI.WsFacturador.cancelarComprobanteRequest inValue = new PruebaCFDI.WsFacturador.cancelarComprobanteRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.cancelarComprobanteRequestBody();
            inValue.Body.xmlCancelacion = xmlCancelacion;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            PruebaCFDI.WsFacturador.cancelarComprobanteResponse retVal = ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).cancelarComprobante(inValue);
            return retVal.Body.cancelarComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.cancelarComprobanteResponse> PruebaCFDI.WsFacturador.wsTimbradoSoap.cancelarComprobanteAsync(PruebaCFDI.WsFacturador.cancelarComprobanteRequest request) {
            return base.Channel.cancelarComprobanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.cancelarComprobanteResponse> cancelarComprobanteAsync(string xmlCancelacion, string usuario, string password) {
            PruebaCFDI.WsFacturador.cancelarComprobanteRequest inValue = new PruebaCFDI.WsFacturador.cancelarComprobanteRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.cancelarComprobanteRequestBody();
            inValue.Body.xmlCancelacion = xmlCancelacion;
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).cancelarComprobanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponse PruebaCFDI.WsFacturador.wsTimbradoSoap.CancelarComprobanteRetenciones(PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest request) {
            return base.Channel.CancelarComprobanteRetenciones(request);
        }
        
        public System.Xml.Linq.XElement CancelarComprobanteRetenciones(string xmlCancelacion, string usuariotimbrado, string passwordtimbrado) {
            PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest inValue = new PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequestBody();
            inValue.Body.xmlCancelacion = xmlCancelacion;
            inValue.Body.usuariotimbrado = usuariotimbrado;
            inValue.Body.passwordtimbrado = passwordtimbrado;
            PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponse retVal = ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).CancelarComprobanteRetenciones(inValue);
            return retVal.Body.CancelarComprobanteRetencionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponse> PruebaCFDI.WsFacturador.wsTimbradoSoap.CancelarComprobanteRetencionesAsync(PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest request) {
            return base.Channel.CancelarComprobanteRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesResponse> CancelarComprobanteRetencionesAsync(string xmlCancelacion, string usuariotimbrado, string passwordtimbrado) {
            PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest inValue = new PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.CancelarComprobanteRetencionesRequestBody();
            inValue.Body.xmlCancelacion = xmlCancelacion;
            inValue.Body.usuariotimbrado = usuariotimbrado;
            inValue.Body.passwordtimbrado = passwordtimbrado;
            return ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).CancelarComprobanteRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponse PruebaCFDI.WsFacturador.wsTimbradoSoap.EnviarCancelacionPFX(PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest request) {
            return base.Channel.EnviarCancelacionPFX(request);
        }
        
        public System.Xml.Linq.XElement EnviarCancelacionPFX(string usuario, string password, PruebaCFDI.WsFacturador.ArrayOfString uuids, byte[] pfx, string passwordPfx, string rfc) {
            PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest inValue = new PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.uuids = uuids;
            inValue.Body.pfx = pfx;
            inValue.Body.passwordPfx = passwordPfx;
            inValue.Body.rfc = rfc;
            PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponse retVal = ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).EnviarCancelacionPFX(inValue);
            return retVal.Body.EnviarCancelacionPFXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponse> PruebaCFDI.WsFacturador.wsTimbradoSoap.EnviarCancelacionPFXAsync(PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest request) {
            return base.Channel.EnviarCancelacionPFXAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.EnviarCancelacionPFXResponse> EnviarCancelacionPFXAsync(string usuario, string password, PruebaCFDI.WsFacturador.ArrayOfString uuids, byte[] pfx, string passwordPfx, string rfc) {
            PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest inValue = new PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.EnviarCancelacionPFXRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            inValue.Body.uuids = uuids;
            inValue.Body.pfx = pfx;
            inValue.Body.passwordPfx = passwordPfx;
            inValue.Body.rfc = rfc;
            return ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).EnviarCancelacionPFXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PruebaCFDI.WsFacturador.obtenerTimbradoResponse PruebaCFDI.WsFacturador.wsTimbradoSoap.obtenerTimbrado(PruebaCFDI.WsFacturador.obtenerTimbradoRequest request) {
            return base.Channel.obtenerTimbrado(request);
        }
        
        public System.Xml.Linq.XElement obtenerTimbrado(string CFDIcliente, string Usuario, string password) {
            PruebaCFDI.WsFacturador.obtenerTimbradoRequest inValue = new PruebaCFDI.WsFacturador.obtenerTimbradoRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.obtenerTimbradoRequestBody();
            inValue.Body.CFDIcliente = CFDIcliente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.password = password;
            PruebaCFDI.WsFacturador.obtenerTimbradoResponse retVal = ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).obtenerTimbrado(inValue);
            return retVal.Body.obtenerTimbradoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.obtenerTimbradoResponse> PruebaCFDI.WsFacturador.wsTimbradoSoap.obtenerTimbradoAsync(PruebaCFDI.WsFacturador.obtenerTimbradoRequest request) {
            return base.Channel.obtenerTimbradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PruebaCFDI.WsFacturador.obtenerTimbradoResponse> obtenerTimbradoAsync(string CFDIcliente, string Usuario, string password) {
            PruebaCFDI.WsFacturador.obtenerTimbradoRequest inValue = new PruebaCFDI.WsFacturador.obtenerTimbradoRequest();
            inValue.Body = new PruebaCFDI.WsFacturador.obtenerTimbradoRequestBody();
            inValue.Body.CFDIcliente = CFDIcliente;
            inValue.Body.Usuario = Usuario;
            inValue.Body.password = password;
            return ((PruebaCFDI.WsFacturador.wsTimbradoSoap)(this)).obtenerTimbradoAsync(inValue);
        }
    }
}
